include:
  - board: nice_nano//zmk
    shield: cosmos_left
  - board: nice_nano//zmk
    shield: cosmos_right
  - board: nice_nano//zmk
    shield: settings_reset

  - board: xiao_ble//zmk
    shield: cosmos_dongle prospector_adapter
    snippet: zmk-usb-logging
  - board: xiao_ble//zmk
    shield: settings_reset
