# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Increase Bluetooth Power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

CONFIG_SVAL_KSCAN=y
CONFIG_ZMK_KSCAN_SVAL_MATRIX=y
# PMW33896 Trackball Support
CONFIG_INPUT_PIXART_PMW3389=y
CONFIG_INPUT_PIXART_PMW3389_USE_OWN_THREAD=y
CONFIG_INPUT_PIXART_PMW3389_THREAD_PRIORITY=5
CONFIG_INPUT_PIXART_PMW3389_THREAD_STACK_SIZE=768
CONFIG_SPI=y

CONFIG_ZMK_POINTING=y

CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=15000