# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Increase Bluetooth Power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

CONFIG_ZMK_POINTING=y

# Prospector Dongle Screen
# CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y