manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: liveseaandsky
      url-base: https://github.com/liveseaandsky
    - name: carrefinho                            # Prospector Dongle
      url-base: https://github.com/carrefinho
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: efogdev
      url-base: https://github.com/efogdev/ # Trackball Sensor Rotation
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: ZMK-Config-Cosmos-1
      remote: liveseaandsky
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: prospector-zmk-module
      remote: carrefinho
      revision: feat/new-status-screens 
    - name: zmk-input-processor-rotate-plane
      remote: efogdev
      revision: main
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
  self:
    path: config
